# Generated by Django 3.2.20 on 2023-10-22 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversaionMessage',
            new_name='ConversationMessage',
        ),
    ]
